version: "3.9"

services:
  go-mattermost:
    build: .
    ports:
      - "8888-8889:8080"
    networks:
      - go_mattermost_app
networks:
  go_mattermost_app:
    # Use a custom driver
    driver: bridge
